app = "qqb"   # CHANGE if taken
primary_region = "fra"         # close to Basel

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
